# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quorum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cquorum.proto\x12\x06quorum\"#\n\x07Replica\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"0\n\x0bReplicaList\x12!\n\x08replicas\x18\x01 \x03(\x0b\x32\x0f.quorum.Replica\"1\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty\"?\n\x0cWriteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"@\n\rWriteResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"T\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x02\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xed\x01\n\x08Registry\x12<\n\x0fRegisterReplica\x12\x0f.quorum.Replica\x1a\x18.quorum.RegisterResponse\x12\x35\n\x0fGetReadReplicas\x12\r.quorum.Empty\x1a\x13.quorum.ReplicaList\x12\x36\n\x10GetWriteReplicas\x12\r.quorum.Empty\x1a\x13.quorum.ReplicaList\x12\x34\n\x0eGetAllReplicas\x12\r.quorum.Empty\x1a\x13.quorum.ReplicaList2\xb3\x01\n\x0fReplica_Service\x12\x34\n\x05Write\x12\x14.quorum.WriteRequest\x1a\x15.quorum.WriteResponse\x12\x31\n\x04Read\x12\x13.quorum.ReadRequest\x1a\x14.quorum.ReadResponse\x12\x37\n\x06\x44\x65lete\x12\x15.quorum.DeleteRequest\x1a\x16.quorum.DeleteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quorum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLICA._serialized_start=24
  _REPLICA._serialized_end=59
  _REPLICALIST._serialized_start=61
  _REPLICALIST._serialized_end=109
  _REGISTERRESPONSE._serialized_start=111
  _REGISTERRESPONSE._serialized_end=160
  _EMPTY._serialized_start=162
  _EMPTY._serialized_end=169
  _WRITEREQUEST._serialized_start=171
  _WRITEREQUEST._serialized_end=234
  _WRITERESPONSE._serialized_start=236
  _WRITERESPONSE._serialized_end=300
  _READREQUEST._serialized_start=302
  _READREQUEST._serialized_end=329
  _READRESPONSE._serialized_start=331
  _READRESPONSE._serialized_end=415
  _DELETEREQUEST._serialized_start=417
  _DELETEREQUEST._serialized_end=446
  _DELETERESPONSE._serialized_start=448
  _DELETERESPONSE._serialized_end=480
  _REGISTRY._serialized_start=483
  _REGISTRY._serialized_end=720
  _REPLICA_SERVICE._serialized_start=723
  _REPLICA_SERVICE._serialized_end=902
# @@protoc_insertion_point(module_scope)
